music_directory    "~/Music"
playlist_directory "~/Music/.playlists"
db_file            "~/.config/mpd/database"
log_file           "syslog"

audio_output {
    type "pipewire"
    name "PipeWire Output"
}
