music_directory    "~/Music"
playlist_directory "~/Music/playlists"
db_file            "~/.local/share/mpd/database"
state_file         "~/.local/share/mpd/state"
log_file           "syslog"

auto_update "yes"
restore_paused "yes"

audio_output {
    type "pipewire"
    name "PipeWire Output"
}
